[package]
name = "beats"
version = "0.1.0"
authors = ["Gardlok"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.6"
anyhow = "1.0.33"

[dev-dependencies]
beats = {path = "../Beats/"}
smol = "1.2.4"
futures = "0.3.7"
