[package]
name = "beats"
version = "0.1.0"
authors = ["Gardlok"]
edition = "2018"

[dependencies]
itertools = "^0.9.0"
influx_db_client = "0.5.0"

[dev-dependencies]
beats = {path = "../beats-lite/"}  # Is this the best way ? 
smol = "^1.2.4"
futures = "^0.3.7"
rust-embed = "^5.6.0"
